app/components/common/dark_mode_toggle/component.html.erb
app/components/common/dark_mode_toggle/component.rb
app/components/common/dark_mode_toggle/preview.rb
app/javascript/controllers/dark_mode_toggle_controller.js
app/javascript/controllers/index.js
app/views/layouts/component_preview.html.erb
test/components/common/dark_mode_toggle_component_test.rb

Implementa um botão para alternar o tema do sistema entre modo escuro e claro:

feat: Add dark mode toggle

---

app/components/ui/card/actions_component.rb
app/components/ui/card/body_component.rb
app/components/ui/card/component.html.erb
app/components/ui/card/component.rb
app/components/ui/card/header_component.html.erb
app/components/ui/card/header_component.rb
app/components/ui/card/header_subtitle_component.rb
app/components/ui/card/header_title_component.rb
app/components/ui/card/media_component.html.erb
app/components/ui/card/media_component.rb
app/components/ui/card/preview.rb
app/components/ui/card/previews/playground.html.erb
test/components/ui/card_component_test.rb

Implementa um componente card. O card não tem slots, mas aplica composição e possui componentes filhos que podem ser posicionados em qualquer ordem dentro do card. Exemplo:
```erb
<%= render UI::Card::Component.new(class: "max-w-sm") do %>
<%= render UI::Card::MediaComponent.new(src: "https://picsum.photos/600/600") %>
<%= render UI::Card::HeaderComponent.new do |header| %>
<% header.with_title.with_content("Read 10 books in 2025") %>
<% header.with_subtitle.with_content("Expanding My World, One Book at a Time") %>
<% end %>
<% end %>
```

feat: Add a card component

---

app/components/ui/avatar/component.html.erb
app/components/ui/avatar/component.rb
app/components/ui/avatar/preview.rb
test/components/ui/avatar_component_test.rb

Adiciona a opção de mostrar um placeholder no componente avatar:

feat: Add avatar placeholder

---

app/components/application_component.rb
app/components/ui/empty_state/component.html.erb
app/components/ui/empty_state/component.rb
app/components/ui/empty_state/preview.rb
app/views/goals/_no_goals.html.erb
app/views/goals/_no_goals_found.html.erb
app/views/goals/index.html.erb
config/locales/pt-BR/views/goals.yml
test/components/ui/empty_state_component_test.rb

- Adiciona o componente `UI::EmptyState::Component` para mostrar mensagens quando uma pesquisa não retorna resultados ou mensagens similares
- Usa o componente empty state na página de metas

feat: Add an empty state component

---

app/controllers/concerns/goal_scoped.rb
app/controllers/dashboard_controller.rb
app/controllers/goals_controller.rb
app/models/current.rb
app/models/goal.rb
app/models/user.rb
bin/setup
db/migrate/20250120140023_add_user_ref_to_goals.rb
db/schema.rb
test/controllers/goals/update_progresses_controller_test.rb
test/controllers/goals_controller_test.rb
test/controllers/homes_controller_test.rb
test/factories/goals.rb
test/test_helper.rb

- Adiciona a coluna `user_id` na tabela `goals`
- Atualiza o GoalsController para buscar goals a partir do usuário logado
- Atualiza o concern GoalScoped para buscar goals a partir do usuário logado
- Adiciona o test helper `sign_in` para criar uma session durante testes
- Corrige os testes que quebraram com a mudança do user
> [!NOTE]
> É recomendado rodar um `bin/setup` para que as migrações sejam executadas corretamente

feat: Add user reference to goals

---

app/views/goals/_goal.html.erb

Move a data e barra de progresso para o final do card. Isso garante que se um card tiver uma descrição longa e sua altura for maior que a dos outros cards, a data e a barra de progresso estarão alinhadas entre os cards:
**Antes:**
**Depois:**

fix: Change cards items placement

---

app/components/ui/breadcrumb/component.rb
app/components/ui/breadcrumb/item_component.rb
app/components/ui/breadcrumb/previews/playground.html.erb
app/views/goals/edit.html.erb
app/views/goals/new.html.erb
test/components/ui/breadcrumb_component_test.rb

Com o componente Breadcrumb criado, podemos aplicar ele nas páginas de Metas. Além disso, aproveitei para mudar a nomenclatura de slots e estilo do componente.

refactor: Apply breadcrumb to goals pages

---

app/views/goals/new.html.erb

Corrigi a ativação do item do breadcrumb da página de criar meta:
Antes:
Depois:

fix: Update breadcrumb item activation for goals new page

---

app/controllers/profiles_controller.rb
app/controllers/registrations_controller.rb
app/models/user.rb
app/views/layouts/_header.html.erb
app/views/layouts/profiles.html.erb
app/views/registrations/new.html.erb
config/locales/pt-BR/views/registrations.yml
config/routes.rb
db/migrate/20250112234157_create_users.rb
db/schema.rb
test/controllers/profiles_controller_test.rb
test/fixtures/users.yml
test/models/user_test.rb

- Adiciona a coluna `username`
- Essa coluna é preenchida durante a criação do usuário usando o `first_name` e `last_name`. Exemplo: John Doe => john.doe
- Em caso de colisão com um username existente, uma string aleatória hexadecimal é adicionada no final. Exemplo: John Doe => `john.doe.1b56b1`
- Atualiza a página do perfil de usuário
- Mostra o handle do user baseado no `username`. Exemplo: @john.doe
- Mostra a header mesmo quando o usuário está deslogado e adiciona um botão `entrar` para redirecionar o usuário para a página de login

feat: Add username column to users table

---

app/controllers/concerns/user_scoped.rb
app/controllers/settings/profiles_controller.rb
app/models/concerns/followable.rb
app/models/user.rb
app/views/layouts/profiles.html.erb
app/views/layouts/profiles/_content.html.erb
app/views/layouts/profiles/_private.html.erb
app/views/settings/profiles/_form.html.erb
config/locales/pt-BR/layouts.yml
config/locales/pt-BR/models/user.yml
db/migrate/20250125134548_add_profile_visibility_to_users.rb
db/schema.rb
test/controllers/profiles/followers_controller_test.rb
test/models/user_test.rb

- Adiciona a coluna `profile_visibility` na tabela `users`
- Adiciona o enum `profile_visiblity` no model User
- Mostra um empty state quando o perfil acessado é privado e o usuário logado não segue ele
> [!NOTE]
> Em outros PRs o botão `Seguir` terá um comportamento diferente se o perfil acessado for privado. Nesses casos, ao invés de um criar um novo Follow entre os usuários, uma solicitação para seguir será enviada para o dono do perfil.

feat: Add profile visibility settings

---

app/models/follow_request.rb
db/migrate/20250125151238_create_follow_requests.rb
db/schema.rb
test/factories/follow_requests.rb
test/models/follow_request_test.rb

- Implementa o model `FollowRequest` que será utilizado para criar o sistema de `solicitar para seguir`
- Implementa o método `FollowRequest#accept!` que permite aceitar uma requisição de follow

feat: Add model FollowRequest

---

app/views/goals/_form.html.erb
app/views/posts/_form.html.erb

Corrigi o espaçamento dos botões dos formulários e aproveitei para usar o componente no lugar no link.
Antes:
Depois:

refactor: fix padding and use button component for forms

---

app/views/profiles/followers/index.html.erb

O dropdown de remover seguidor está aparecendo para os visitantes do perfil. Isso acontece porque a lista de seguidores utiliza fragment caching e a chave do partial é o id do seguidor. 
Como o mesmo seguidor pode ser renderizado de duas formas diferentes (com ou sem dropdown) de acordo com quem está visitando o perfil, o visitante pode acessar o perfil e ver o dropdown que deveria aparecer apenas para o dono.
A solução é adicionar o `Current.user` na chave da cache de cada seguidor. Dessa forma, o dono do perfil sempre vai ver o seguidor com o dropdown e os visitantes não terão acesso a ele.

fix: Add Current.user to follower cache key

---

app/components/common/dark_mode_toggle/component.rb
app/components/common/dark_mode_toggle/preview.rb
app/views/layouts/_header.html.erb
config/application.rb
test/components/common/dark_mode_toggle_component_test.rb

- Adiciona a pasta `app/components/features` para componentes específicos de um domínio. Ex:
-  `app/components/goals/card/component.rb`
- Utiliza a opção `collapse` do zeitwerk para não criar os módulos Features e Common
- Remove o módulo Common do componente DarkModeToggle

feat: Add features components folder

---

Gemfile
Gemfile.lock
app/controllers/application_controller.rb
app/controllers/feed_controller.rb
app/helpers/application_helper.rb
app/helpers/feed_helper.rb
app/models/entry.rb
app/views/entries/entryables/_post.html.erb
app/views/feed/_entry.html.erb
app/views/feed/_next_page.html.erb
app/views/feed/_no_entries.html.erb
app/views/feed/index.html.erb
app/views/feed/index.turbo_stream.erb
config/initializers/pagy.rb
config/locales/pt-BR/views/feed.yml
config/routes.rb
test/controllers/feed_controller_test.rb
test/factories/entries.rb
test/models/entry_test.rb

Adiciona o controller FeedController para listar posts do usuário e seus seguidores. No PR #79, o feed será adicionado na página Home.
**Mudanças:**
- Adiciona a gem `pagy`
- Adiciona o FeedController
- Lista as entries do usuário logado
- Adiciona infinite loading na listagem de publicações do FeedController
- Adiciona o scope `feed` em Entry para listar as postagens do feed do usuário logado
> [!NOTE]
> O design dos posts vai ser alterado no PR #79

feat: Add the feed controller

---

app/models/entry.rb
app/models/entry/like.rb
db/migrate/20250202144844_create_entry_likes.rb
db/schema.rb
test/factories/entries.rb
test/factories/entry/likes.rb
test/models/entry/like_test.rb
test/models/entry_test.rb

Criei o modelo `Entry::Like` que será responsável pela feature de likes nos posts e comentários do Goals.
O modelo possui os seguintes atributos:
- `entry`
- `user` (o usuário que está curtindo a `Entry`)
Cada combinação de `entry_id` e `user_id` deve ter no máximo uma `Entry:Like`, garantindo que um usuário não possa curtir a mesma `Entry` mais de uma vez.

feat: Add Entry::Likes model

---

Gemfile
Gemfile.lock
app/components/common/image_preview_card/component.html.erb
app/components/common/image_preview_card/component.rb
app/components/common/image_preview_card/file_input_component.rb
app/components/common/image_preview_card/hidden_input_component.rb
app/components/common/image_preview_card/image_component.rb
app/components/ui/button/component.rb
app/components/ui/button/preview.rb
app/controllers/posts_controller.rb
app/helpers/custom_form_builder.rb
app/javascript/controllers/index.js
app/javascript/controllers/multiple_image_preview_controller.js
app/javascript/controllers/removal_controller.js
app/models/post.rb
app/views/posts/_form.html.erb
app/views/posts/_preview_container.html.erb
config/locales/pt-BR/models/posts.yml
config/locales/pt-BR/views/posts.yml
test/components/common/image_preview_card_test.rb
test/components/ui/dropzone_component_test.rb
test/controllers/posts_controller_test.rb
test/models/post_test.rb
test/test_helper.rb

- Adicona a gem `active_storage_validations` para validar as imagens do Post
- Adiciona um dropzone no formulário do post
- Adiciona o componente ImagePreviewCard para mostrar o preview de uma imagem
**Formulário de criar post:**

feat: Add image upload to posts form

---

app/controllers/goals/progress_changes/posts_controller.rb
app/views/goals/progress_changes/posts/_form.html.erb
config/locales/pt-BR/views/goals.yml
test/controllers/goals/progress_changes/posts_controller_test.rb

Adiciona upload de imagens no formulário de posts de atualização de progresso:

feat: Add image upload to progress update posts

---

test/models/entry_test.rb
test/models/goal/progress_change_test.rb
test/models/goal_test.rb
test/models/user_test.rb

Para melhorar a performance dos testes, troquei o `create` por `new` em alguns casos.

refactor: Replace `create` with `new` in tests

---

app/controllers/homes_controller.rb
app/models/goal.rb
app/views/goals/_goal.html.erb
app/views/homes/_goal.html.erb
app/views/homes/show.html.erb
config/locales/pt-BR/views/homes.yml
test/models/goal_test.rb

- Adiciona um link `Ver minhas metas` quando o usuário tem mais de 5 metas pendentes
- Corrige o tamanho do card do goal no mobile (não estava preenchedo o espaço restante no mobile)

feat: Add see more goals list

---

app/controllers/entries/comments_controller.rb
app/controllers/feed_controller.rb
app/helpers/posts/comments_helper.rb
app/views/entries/comments/_comment_section.html.erb
app/views/entries/comments/_form.html.erb
app/views/entries/comments/_load_more_button.html.erb
app/views/entries/comments/create.turbo_stream.erb
app/views/entries/comments/index.turbo_stream.erb
app/views/entries/comments/new.html.erb
app/views/entries/entryables/_comment.html.erb
app/views/entries/entryables/_post.html.erb
app/views/entries/likes/_update_likes.turbo_stream.erb
config/locales/pt-BR/views/entries.yml
config/routes.rb
test/controllers/posts/comments_controller_test.rb
test/factories/entries.rb

Implementa a funcionalidade de comentar em posts. Usuários podem comentar nos seguintes casos:
- O perfil do dono da entry é público
- A entry pertence ao usuário logado
- O usuário logado segue o dono da entry
**Imagem da tela de comentários:**

feat: Add create comment

---

app/models/entry.rb
test/models/entry_test.rb

O scope `feed` não está filtrando corretamente pelo `entryable_type`, por causa disso, comentários são carregados no feed como se fossem posts e dão erro:

fix: Changes feed scope filter order

---

app/models/comment.rb
app/models/entry.rb
test/models/comment_test.rb

Corrige a criação de comentários. Ao tentar criar comentários em produção, aparece um `content missing`. Os logs mostram que está dando um erro no banco de unique constraint. O problema parece ser que no Comment existe um `has_one :entry` (através do concern Entryable) e `belongs_to :entry`:
A solução é mudar o `belongs_to :entry` para `belongs_to :parent`.

fix: Fix comment creation

---

app/views/entries/entryables/_post.html.erb

Percebi que tá rolando uns bugs visuais na hora de "Dar kudos" e visualizar eles, por exemplo, quando eu curto um post e abro para visualizar, aparece nenhuma curtida ou apenas a curtida que já existia.
https://github.com/user-attachments/assets/ceabf1b8-b867-4e5a-bbd2-67160d7cbb58

fix: Add loading lazy attribute to avoid visual bugs

---

Gemfile
Gemfile.lock
config/deploy.yml
public/robots.txt

Configura o arquivo `robots.txt` para definir que buscadores indexem apenas as páginas de login e cadastro.

config: Setup robots.txt

---

app/views/layouts/_header.html.erb
config/locales/pt-BR/layouts.yml

Adicionei atalhos para criar post e meta no dropdown do header:

feat: Add shortcut to create post and goals

---

app/controllers/entries/likes_controller.rb
config/locales/pt-BR/views/entries.yml
config/routes.rb

No controller de likes existem redirects para a página show das entryables, mas não há entryables com uma página show. Esse PR adiciona um fallback que aponta a página de show das entryables para a home.

fix: Add fallback for entryables without show page

---

app/controllers/goals_controller.rb
app/models/goal.rb
app/views/goals/_form.html.erb
app/views/goals/_goal.html.erb
config/locales/pt-BR/models/goals.yml
config/locales/pt-BR/views/goals.yml
db/migrate/20250222193345_add_visibility_to_goals.rb
db/schema.rb
test/models/goal_test.rb

- Adiciona a coluna `visibility` na tabela `goals`
- Adiciona um ícone no card da meta para indicar que a meta é privada

feat: Add visibility control to goals

---

app/components/features/entries/like_count/component.html.erb
app/models/entry/like.rb
app/views/entries/likes/index.html.erb
db/migrate/20250223001713_add_likes_count_to_entries.rb
db/migrate/20250223002249_populate_entry_likes_count.rb
db/schema.rb

Adiciona `counter_cache` para substituir queries do tipo `entry.likes.count` por `entry.likes_count`.
**Antes:**
**Depois:**

feat: Add counter cache for likes

---

app/controllers/profiles/goals_controller.rb
app/models/goal/progress_change.rb
app/views/goals/update_progresses/edit.html.erb
app/views/layouts/profiles/_content.html.erb
app/views/profiles/followers/_follower.html.erb
app/views/profiles/followers/_pending_follow_requests.html.erb
app/views/profiles/goals/_next_page.html.erb
app/views/profiles/goals/_no_goals.html.erb
app/views/profiles/goals/index.html.erb
app/views/profiles/goals/index.turbo_stream.erb
app/views/profiles/show.html.erb
config/locales/pt-BR/views/profiles.yml
config/routes.rb
test/controllers/profiles/goals_controller_test.rb
test/factories/goals.rb
test/models/goal/progress_change_test.rb
test/policies/profiles/goal_policy_test.rb

Adiciona listagem de metas no perfil do usuário. Quando o usuário logado é o dono do perfil, as metas mostram um dropdown.
**O que o dono do perfil vê:**
**O que os visitantes do perfil veem:**
**O que o dono do perfil vê quando não há metas cadastradas:**
**O que o vistantes veem quando não há metas cadastradas:**

feat: Add user goals to profile

---

app/controllers/feed_controller.rb
app/controllers/profiles/goals_controller.rb
app/controllers/profiles_controller.rb
app/views/feed/_next_page.html.erb
app/views/profiles/_next_page.html.erb
app/views/profiles/goals/_next_page.html.erb

Corrige o comportamento do botão de seguir. Atualmente, depois que o botão é clicado, a página não atualiza e o botão permanece igual. O comportamento esperado é que o botão mudasse de `Seguir` para `Parar de seguir`.
Esse problema aconteceu, porque, depois que a rota de seguir usuário é chamada, ocorre um redirect para o perfil do usuário no formato `turbo_stream`, o que faz o controller de posts adicionar novos posts no feed do perfil ao invés de atualizar a página.

fix: Follow button does not update

---

app/controllers/profiles/feed_entries_controller.rb
app/models/concerns/entryable.rb
app/policies/entry_policy.rb
app/policies/profiles/feed_entry_policy.rb
app/views/entries/entryables/_post.html.erb
app/views/feed/_entry.html.erb
app/views/feed/index.html.erb
app/views/goals/_goal.html.erb
app/views/posts/destroy.turbo_stream.erb
app/views/profiles/_entry.html.erb
app/views/profiles/feed_entries/destroy.turbo_stream.erb
app/views/profiles/show.turbo_stream.erb
config/initializers/pagy.rb
config/locales/pt-BR/views/entries.yml
config/locales/pt-BR/views/posts.yml
config/locales/pt-BR/views/profiles.yml
config/routes.rb
test/models/post_test.rb
test/policies/entry_policy_test.rb
test/policies/profiles/feed_entry_policy_test.rb

Implementa a remoção de posts a partir do perfil do usuário. Adicionei a action destroy em um novo controller `Profiles::FeedEntriesController` ao invés de adicionar em `PostsController`, porque depois de remover o post, se não houver mais posts, eu preciso adicionar o empty state no feed. Como o empy state do perfil é diferente do empty state do feed, então preferi separar esses controllers ao invés de ter que tratar esses casos no turbo_stream.

feat: Add a destroy post button for the profile feed posts

---

app/components/features/notifications/item_component.html.erb
app/components/features/notifications/item_component.rb
app/components/features/notifications/list_component.html.erb
app/components/features/notifications/list_component.rb
app/components/features/notifications/types/notification_like_component.html.erb
app/components/features/notifications/types/notification_like_component.rb
app/models/user.rb
config/locales/pt-BR/features.yml
test/components/features/notifications/item_component_test.rb
test/components/features/notifications/list_component_test.rb
test/components/features/notifications/types/notification_like_component_test.rb
test/factories/entry/likes.rb
test/factories/notifications.rb
test/factories/user_notifications.rb

Quando o usuário possui notificações:
Quando o usuário não possui notificações:
Débitos técnicos para o próximo PR:
- Ajustar o nome da relação de User e UserNotification para ficar apenas "user_notification" (só mexi pq precisava incluir essa relação pro teste passar)
- Ajustar as factories (a ideia é criar traits com as opções de notifiable igual como está as de entries)

feat: Implement notification components

---

app/components/ui/counter/button_component.rb
app/javascript/controllers/railsui/counter_input_controller.js
app/javascript/controllers/sum_updater_controller.js
app/views/goals/update_progresses/edit.html.erb

Adiciona o input `counter` no modal de atualizar progresso da meta:

feat: Add counter input to progress update

---

app/jobs/entry/mention_syncer_job.rb
app/models/comment.rb
app/models/entry.rb
app/models/entry/mention_cleaner.rb
app/models/entry/mention_importer.rb
app/models/entry/mention_syncer.rb
app/models/handle.rb
app/models/handle_text_parser.rb
app/models/post.rb
app/models/user.rb
test/models/comment_test.rb
test/models/entry/mention_cleaner_test.rb
test/models/entry/mention_importer_test.rb
test/models/entry/mention_syncer_test.rb
test/models/entry_test.rb
test/models/handle_text_parser_test.rb
test/models/post_test.rb
test/models/user_test.rb

Implementa o método `Entry#sync_mentions_later` que permite extrair e salvar menções feitas em posts e comentários. As menções são extraídas pela classe `HandleTextParser` e criadas no banco com a classe `Entry::MentionSyncer`.

feat: Add mentions to posts and entries

---

app/components/features/notifications/types/notification_like_component.html.erb
app/components/features/notifications/types/notification_like_component.rb
app/components/ui/typography/component.rb
app/controllers/posts_controller.rb
app/policies/post_policy.rb
app/views/entries/entryables/_post.html.erb
app/views/homes/show.html.erb
app/views/posts/show.html.erb
app/views/posts/show.turbo_stream.erb
app/views/registrations/_form.html.erb
app/views/sessions/_form.html.erb
config/locales/pt-BR/features.yml
config/locales/pt-BR/views/posts.yml
config/routes.rb
test/controllers/posts_controller_test.rb
test/policies/post_policy_test.rb

- Adiciona a página do post
- Atualiza o componente de notificação para redirecionar para os posts
- Corrige a contagem de metas que era mostrada na página principal (aparecia sempre 5 metas)
**Notificações:**
**Página da publicação:**
**Demonstração:**
https://github.com/user-attachments/assets/f4315175-f2be-4110-9e43-4310c9b8034d

feat: Add post show page

---

app/models/notification_factory.rb
app/models/notification_notifier.rb
config/initializers/event_subscriber.rb
test/models/notification_factory_test.rb
test/models/notification_notifier_test.rb

- Adiciona a classe `NotificationFactory` para construir os diferentes tipos de notificações
- Adiciona a classe `NotificationNotifier` para criar e enviar notificações
- Atualiza `config/initializers/event_subscriber.rb` para utilizar as novas classes

refactor: Add a notification notifier

---

app/components/application_component.rb
app/components/attribute_merger.rb
app/components/ui/card/media_component.rb
app/components/ui/progress_bar/component.rb
app/components/ui/toast/component.rb
test/components/attributes_merger_test.rb

Move a inicialização do TailwindMerger para uma constante. Quando um componente é instanciado, uma instância do TailwindMerger é criada. Essa criação de objeto adiciona um overhead na renderização dos componentes.
**Antes:**
**Depois:**
De `3.723k` iterações em 5 segundos para `3.519M`.
<details>
<summary>Script usado no benchmark</summary>
```ruby
require_relative 'config/environment'
require 'benchmark/ips'
class DummyComponent < ApplicationComponent
def default_attrs
{ class: "bg-white text-black" }
end
end
Benchmark.ips do |x|
x.config(time: 5, warmup: 2)
x.report("basic init") do
DummyComponent.new
end
x.report("init with class") do
DummyComponent.new(class: "bg-red-500 text-white")
end
x.report("init with mixed attrs") do
DummyComponent.new(id: "main", data: { controller: "test" }, …
```

refactor: Move tailwind merger to const

---

app/views/layouts/_header.html.erb

A central de notificações mostra o horário em que cada notificação foi recebida. O componente da lista de notificações estava envolvido em um bloco de cache, então o horário de recebimento das notificações não estava sendo atualizado. Este PR remove a cache do componente de listar as notificações.

feat: Remove notifications list cache
