goals-rest/goals

app/helpers/custom_form_builder.rb, app/helpers/forms_helper.rb, config/initializers/field_error_proc.rb
O que você acha dessa abordagem @karinevieira? Eu usei o form builder para adicionar as classes do `railsui` nos inputs principais (text_field, select, check_box, etc). Também criei o helper `custom_form_with` para consumir o form builder.
=> feat: Setup custom form builder

Gemfile, Gemfile.lock, db/migrate/20250112182022_create_active_storage_tables.active_storage.rb, db/schema.rb
Instalei o Active Storage para lidar com os uploads, nesse primeiro momento só estou habilitando para ambiente local e de teste, mas assim que tivermos um ambiente de produção posso ativar o upload para S3.
=> config: Install Active Storage to upload files

Gemfile, Gemfile.lock, app/channels/application_cable/connection.rb, app/controllers/application_controller.rb, app/controllers/concerns/authentication.rb, app/controllers/passwords_controller.rb, app/controllers/sessions_controller.rb, app/mailers/passwords_mailer.rb, app/models/current.rb, app/models/session.rb, app/models/user.rb, app/views/passwords/edit.html.erb, app/views/passwords/new.html.erb, app/views/passwords_mailer/reset.html.erb, app/views/passwords_mailer/reset.text.erb, app/views/sessions/new.html.erb, config/routes.rb, db/migrate/20250112234157_create_users.rb, db/migrate/20250112234158_create_sessions.rb, db/schema.rb, test/fixtures/users.yml, test/mailers/previews/passwords_mailer_preview.rb, test/models/user_test.rb
Roda o comando `bin/rails generate authentication` para gerar o boilerplate de autenticação do Rails.
=> config: Setup authentication

Gemfile, Gemfile.lock, app/models/goal.rb, config/locales/pt-BR/models.yml, db/migrate/20250112183014_create_goals.rb, db/schema.rb, test/factories/goals.rb, test/models/goal_test.rb
Criei o modelo Goal com os campos:
- `title`: título da meta, é obrigatório e será permitido até 60 caracteres.
- `description`: descrição da meta, será permitido até 100 caracteres.
- `start_date`: data de início da meta, é obrigatório.
- `end_date`: data final da meta, é obrigatório e não pode ser menor que a data de início.
- `current`: a unidade ou quantidade atual da meta, será usada para calcular o progresso da meta e também é obrigatório.
- `target`: a unidade ou quantidade alvo da meta, será usada para calcular o progresso da meta e também é obrigatório.
- `status`: o status da meta, começa como "pendente".
O progresso da meta será calculado por (`current / target * 100`)
=> feat: Create Goal model

app/controllers/dashboard/goals_controller.rb, app/models/goal.rb, app/views/dashboard/goals/_form.html.erb, app/views/dashboard/goals/new.html.erb, app/views/layouts/dashboard.html.erb, config/locales/pt-BR/models/goals.yml, config/locales/pt-BR/views/dashboard/goals.yml, config/routes.rb, test/controllers/dashboard/goals_controller_test.rb
=> feat: Add create goal page

app/components/ui/progress_bar/component.html.erb, app/components/ui/progress_bar/component.rb, app/components/ui/progress_bar/preview.rb, test/components/ui/progress_bar_component_test.rb
Implementa um componente de barra de progresso:
=> feat: Add a progress bar component

app/views/layouts/_header.html.erb, app/views/layouts/application.html.erb, app/views/shared/_logo_color.html.erb
- Melhora a experiência no dark mode
- Habilita o placeholder no avatar do usuário
- Adiciona um toggle para controlar o tema atual
=> refactor: Dashboard improvements

app/components/ui/toast/component.html.erb, app/components/ui/toast/component.rb, app/components/ui/toast/preview.rb, tailwind.config.js, test/components/ui/toast_component_test.rb
Implementa o componente Toast:
=> feat: Add toast component

app/components/ui/badge/component.html.erb, app/components/ui/badge/component.rb, app/components/ui/badge/dismiss_button_component.html.erb, app/components/ui/badge/dismiss_button_component.rb, app/components/ui/badge/preview.rb, test/components/ui/badge_component_test.rb
Implementa o componente Badge:
=> feat: Add a badge component

app/components/ui/dropdown/component.rb, app/controllers/dashboard/goals_controller.rb, app/models/goal.rb, app/views/dashboard/goals/_goal.html.erb, app/views/dashboard/goals/index.html.erb, config/locales/pt-BR/custom_date_formats.yml, config/locales/pt-BR/views/dashboard/goals.yml, config/routes.rb, test/controllers/dashboard/goals_controller_test.rb, test/models/goal_test.rb
=> feat: Add goals list page

Gemfile, Gemfile.lock, app/controllers/registrations_controller.rb, app/models/user.rb, app/views/registrations/_form.html.erb, db/migrate/20250112234157_create_users.rb, db/schema.rb, db/seeds.rb, test/controllers/registrations_controller_test.rb, test/factories/users.rb, test/models/user_test.rb
Implementa o cadastro de usuários.
=> feat: Add user registration

app/controllers/goals_controller.rb, app/views/goals/_form.html.erb, app/views/goals/_goal.html.erb, app/views/goals/edit.html.erb, config/locales/pt-BR/views/goals.yml, config/routes.rb, test/controllers/goals_controller_test.rb
=> feat: Implement edit goal page

app/components/ui/toast/component.html.erb, app/components/ui/toast/component.rb, app/views/layouts/dashboard.html.erb, app/views/shared/_flash.html.erb
=> feat: Replace flash with toast

app/components/ui/tab_nav/component.html.erb, app/components/ui/tab_nav/component.rb, app/components/ui/tab_nav/preview.rb, app/components/ui/tab_nav/tab_component.html.erb, app/components/ui/tab_nav/tab_component.rb, test/components/ui/tab_nav_component_test.rb
Implementa o componente TabNav:
=> feat: Add tab nav component

app/components/ui/breadcrumb/component.rb, app/controllers/profiles_controller.rb, app/helpers/profiles_helper.rb, app/views/layouts/_header.html.erb, app/views/layouts/profiles.html.erb, app/views/layouts/profiles/_sidebar.html.erb, app/views/profiles/show.html.erb, config/locales/pt-BR/layouts.yml, config/routes.rb, test/controllers/profiles_controller_test.rb
=> feat: Implementa a tela de perfil de usuário

app/controllers/follows_controller.rb, app/helpers/follows_helper.rb, app/models/concerns/followable.rb, app/models/follow.rb, app/models/user.rb, app/views/layouts/profiles.html.erb, app/views/layouts/profiles/_sidebar.html.erb, config/locales/pt-BR/layouts.yml, config/locales/pt-BR/views/follows.yml, config/routes.rb, db/migrate/20250121173433_create_follows.rb, db/schema.rb, test/controllers/follows_controller_test.rb, test/controllers/profiles_controller_test.rb, test/factories/follows.rb, test/models/follow_test.rb, test/models/user_test.rb
- Cria a tabela `follows` para representar a relação de seguidor e seguido entre usuários
- Implementa o controller FollowsController para criar e deletar follows
- Implementa o funcionamento do botão `Seguir` que fica no perfil do usuário
- Adiciona o botão `Parar de seguir` no perfil do usuário
- Adiciona testes
=> feat: Add user following

app/controllers/application_controller.rb, app/controllers/concerns/user_scoped.rb, app/controllers/follows_controller.rb, app/controllers/profiles/followers_controller.rb, app/controllers/profiles_controller.rb, app/helpers/profiles/followers_helper.rb, app/models/user.rb, app/views/goals/_goal.html.erb, app/views/layouts/profiles.html.erb, app/views/profiles/followers/_follower.html.erb, app/views/profiles/followers/index.html.erb, config/locales/pt-BR/layouts.yml, config/locales/pt-BR/views/follows.yml, config/locales/pt-BR/views/profiles.yml, config/routes.rb, test/controllers/follows_controller_test.rb, test/controllers/profiles/followers_controller_test.rb, test/models/user_test.rb
**Visão do usuário logado:**
**Visão do visitante:**
=> feat: Add followers page

app/models/post.rb, app/models/user.rb, db/cable_schema.rb, db/cache_schema.rb, db/migrate/20250130133350_create_posts.rb, db/queue_schema.rb, db/schema.rb, test/factories/posts.rb, test/factories/users.rb, test/models/post_test.rb, test/models/user_test.rb
Criei a tabela posts, com os seguintes campos:
- `owner_id` (User): é o usuário, dono do post.
- `title` (String): é o título do post.
- `body` (Text): é o conteúdo do post.
A tabela tem os seguintes relacionamentos:
- O post pertence á um usuário
- Um usuário pode ter vários posts
E também é realizado as validações abaixo:
- `title`: será obrigatório e não pode ter mais de 60 caracteres
- `body`: será obrigatório
=> feat: Create posts table

app/controllers/posts_controller.rb, app/models/current.rb, app/views/posts/_form.html.erb, app/views/posts/new.html.erb, config/locales/pt-BR/models/posts.yml, config/locales/pt-BR/views/posts.yml, config/routes.rb, test/controllers/posts_controller_test.rb
=> feat: Implement action to create post

app/controllers/follow_requests_controller.rb, app/helpers/follow_requests_helper.rb, app/models/user.rb, app/views/follow_requests/_follow_request.html.erb, app/views/follow_requests/_no_follow_requests.html.erb, app/views/follow_requests/index.html.erb, app/views/profiles/followers/_pending_follow_requests.html.erb, app/views/profiles/followers/index.html.erb, config/locales/pt-BR/views/follow_requests.yml, config/locales/pt-BR/views/profiles.yml, config/routes.rb, test/controllers/follow_requests_controller_test.rb, test/models/user_test.rb
Implementa a listagem de solicitações para seguir:
=> feat: Add list follow requests

app/controllers/follow_requests_controller.rb, app/views/follow_requests/_follow_request.html.erb, config/locales/pt-BR/views/follow_requests.yml, config/routes.rb, test/controllers/follow_requests_controller_test.rb
Este PR adiciona o botão de rejeitar solicitação para seguir.
=> feat: Add reject follow request

app/controllers/follow_requests/accept_follow_requests_controller.rb, app/controllers/follow_requests_controller.rb, app/controllers/follows_controller.rb, app/controllers/profiles/follow_requests_controller.rb, app/helpers/profiles/follow_requests_helper.rb, app/views/follow_requests/_follow_request.html.erb, app/views/layouts/profiles.html.erb, config/locales/pt-BR/layouts.yml, config/locales/pt-BR/views/follow_requests.yml, config/locales/pt-BR/views/profiles.yml, config/routes.rb, test/controllers/follow_requests/accept_follow_requests_controller_test.rb, test/controllers/follow_requests_controller_test.rb, test/controllers/follows_controller_test.rb, test/controllers/profiles/follow_requests_controller_test.rb
Este PR implementa apenas o backend da funcionalidade de enviar solicitação para seguir e recusar.
=> feat: Add send follow request

app/models/goal.rb, app/models/goal/progress_change.rb, db/migrate/20250201011935_create_goal_progress_changes.rb, db/schema.rb, test/factories/goal/progress_changes.rb, test/models/goal/progress_change_test.rb, test/models/goal_test.rb
Implementa o model `Goal::ProgressChange` para salvar o histórico de mudanças de uma meta.
=> feat: Add model Goal::ProgressChange

config/deploy.yml
Atualiza o `deploy.yml` para usar as variáveis de ambiente definidas pelo usuário.
=> config: Replace hard coded strings with env variables

app/assets/stylesheets/application.tailwind.css, app/assets/stylesheets/railsui/buttons.css, app/assets/stylesheets/railsui/headings.css, custom_preset.js, tailwind.config.js
- Substitui o preset do railsui por um preset customizado
- Adiciona o css para os botões e headings
=> config: Replace shepherd preset with a custom one

app/components/features/goals/progress_indicator/component.html.erb, app/components/features/goals/progress_indicator/component.rb, app/components/features/goals/progress_indicator/preview.rb, app/models/goal/progress_change.rb, config/locales/pt-BR/features.yml, test/components/features/goals/progress_indicator_test.rb, test/models/goal/progress_change_test.rb
Implementa o componente `ProgressIndicator`:
=> feat: Add ProgressIndicator component

app/models/concerns/entryable.rb, app/models/entry.rb, db/migrate/20250202135746_create_entries.rb, db/schema.rb, test/factories/entries.rb, test/models/entry_test.rb
- Adiciona o model Entry
- Adicona o concern Entryable
=> feat: Add model Entry

app/controllers/posts_controller.rb, app/models/current.rb, app/models/entry.rb, app/models/post.rb, app/models/user.rb, db/migrate/20250202140755_remove_owner_reference_from_posts.rb, db/schema.rb, test/factories/posts.rb, test/models/entry_test.rb, test/models/post_test.rb, test/models/user_test.rb
- Adiciona o concern Entryable em Post
- Atualiza o controller de post para criar a Entry e o Post juntos
=> feat: Add entryable concern in Post model

test/models/goal_test.rb, test/models/post_test.rb
Removi os contextos e troquei o should por test nos testes para seguir o padrão do projeto
=> refactor: Remove context and switch should for test

app/controllers/goals/progress_changes/posts_controller.rb, app/controllers/goals/update_progresses_controller.rb, app/helpers/custom_form_builder.rb, app/helpers/goals/goal_progress_changes/posts_helper.rb, app/models/post.rb, app/views/goals/progress_changes/posts/_form.html.erb, app/views/goals/progress_changes/posts/new.html.erb, config/locales/pt-BR/views/goals.yml, config/routes.rb, db/migrate/20250202211320_add_goal_progress_changes_ref_to_posts.rb, db/schema.rb, test/controllers/goals/progress_changes/posts_controller_test.rb, test/controllers/goals/update_progresses_controller_test.rb
Adiciona a tela de criar post de atualização de progresso:
=> feat: Add create goal progress update post

app/components/ui/skeleton/component.rb, app/components/ui/skeleton/preview.rb, app/components/ui/skeleton/previews/card.html.erb, test/components/ui/skeleton_component_test.rb
=> feat: Add Skeleton component

Gemfile, Gemfile.lock, app/controllers/feed_controller.rb, app/views/homes/_feed_skeleton.html.erb, app/views/homes/show.html.erb
Mostra um skeleton no lugar do feed enquanto os posts estão carregando:
=> feat: Show a feed skeleton while the feed is loading

app/components/ui/dropzone/component.html.erb, app/components/ui/dropzone/component.rb, app/components/ui/dropzone/file_input_component.rb, app/components/ui/dropzone/preview.rb, config/locales/pt-BR/ui.yml, test/components/ui/dropzone_component_test.rb
Adiciona o componete Drozpone:
=> feat: Add dropzone component

.prettierrc, app/components/application_component.rb, app/components/ui/carousel/component.html.erb, app/components/ui/carousel/component.rb, app/components/ui/carousel/indicator_component.rb, app/components/ui/carousel/next_button_component.html.erb, app/components/ui/carousel/next_button_component.rb, app/components/ui/carousel/preview.rb, app/components/ui/carousel/previews/playground.html.erb, app/components/ui/carousel/previous_button_component.html.erb, app/components/ui/carousel/previous_button_component.rb, app/components/ui/carousel/slide_component.rb, app/components/ui/carousel/viewport_component.html.erb, app/components/ui/carousel/viewport_component.rb, app/javascript/controllers/carousel_controller.js, app/javascript/controllers/index.js, eslint.config.mjs, package.json, test/components/ui/carousel_component_test.rb, yarn.lock
Implementa o componente Carousel:
=> feat: Add Carousel component

app/controllers/entries/likes_controller.rb, app/models/entry.rb, test/models/entry_test.rb
Dividi o escopo do `feed` e criei o `visible` para reaproveitar a lógica e utilizar no `Entries::LikesController`.
=> refactor: Improve entry visibility logic

app/components/ui/card/header_subtitle_component.rb, app/views/entries/entryables/_post.html.erb, app/views/goals/_goal.html.erb, app/views/homes/show.html.erb
- Adiciona a classe `font-heading` em alguns títulos e descrições para deixar mais parecido com o estilo do railsui
- Adiciona links para o perfil no nome e foto do usuário logado
=> feat: Add style improvements

app/controllers/concerns/enforce_turbo_request.rb, app/controllers/entries/likes_controller.rb, app/views/entries/entryables/_post.html.erb, app/views/entries/likes/_like.html.erb, app/views/entries/likes/_load_more_button.html.erb, app/views/entries/likes/_update_likes.turbo_stream.erb, app/views/entries/likes/index.html.erb, app/views/entries/likes/index.turbo_stream.erb, config/locales/pt-BR/views/entries.yml, config/routes.rb, test/controllers/entries/likes_controller_test.rb
Adicionei um modal para poder visualizar quem curtiu a publicação:
Quando ainda não teve nenhuma curtida:
Aceito sugestões de design :P
=> feat: List kudos

app/controllers/entries/comments_controller.rb, app/views/entries/comments/_comment_section.html.erb
Ordena os comentários por ordem crescente de data de criação.
=> feat: Order comments ascending by created at date

Gemfile, Gemfile.lock
Adiciona a gem [action_policy](https://github.com/palkan/action_policy).
=> config: Add action_policy gem

config/deploy.yml
Adiciona o prefixo `GOALS_` nas variáveis do arquivo de deploy do kamal. Essa mudança diminui a chance de conflito de nomes com variáveis já existentes no sistema.
=> config: Add GOALS_ prefix to deploy variables

app/components/ui/tooltip/body_component.html.erb, app/components/ui/tooltip/body_component.rb, app/components/ui/tooltip/component.html.erb, app/components/ui/tooltip/component.rb, app/components/ui/tooltip/preview.rb, app/components/ui/tooltip/trigger_component.rb, app/javascript/controllers/index.js, app/javascript/controllers/tooltip_controller.js, app/views/rui/shared/_railsui_head.html.erb, package.json, test/components/ui/tooltip_component_test.rb, yarn.lock
- Adiciona o componente Tooltip
- Remove o pacote `tippy.js` por estar desafado
- Adiciona o pacote `@floating-ui/dom`
=> feat: Add tooltip component

app/controllers/profiles_controller.rb, app/models/entry.rb, app/views/layouts/profiles.html.erb, app/views/profiles/_entry.html.erb, app/views/profiles/_next_page.html.erb, app/views/profiles/_no_entries.html.erb, app/views/profiles/show.html.erb, app/views/profiles/show.turbo_stream.erb, config/locales/pt-BR/views/profiles.yml, test/models/entry_test.rb
=> feat: Add user entries in profile

app/controllers/concerns/authentication.rb, app/controllers/profiles_controller.rb, app/policies/application_policy.rb, app/policies/goal_policy.rb, app/policies/profiles/goal_policy.rb, app/policies/profiles_policy.rb, app/views/goals/_goal.html.erb, test/policies/goal_policy_test.rb, test/policies/profiles_policy_test.rb
- Adiciona a policy `ApplicationPolicy`
- Adiciona a policy `ProfilesPolicy` para ser a policy base do perfil do usuário
- Adiciona a policy `GoalPolicy`
- Adiciona a policy `Profiles::GoalPolicy`
=> feat: Add goals policy

bin/dev
Adicionei alguns comandos para instalar as dependências quando o startar o servidor
=> config: Ensure all gems and npm packages are installed in dev script

app/models/goals_progress_calendar_builder.rb, app/models/user.rb, app/views/layouts/profiles.html.erb, test/models/user_test.rb
=> fix: Change follow button position

app/controllers/profiles/goals_controller.rb, app/models/goal.rb, app/policies/profiles/goal_policy.rb, app/policies/profiles_policy.rb, app/views/goals/_goal.html.erb, app/views/profiles/goals/show.html.erb, config/locales/pt-BR/models/goals.yml, config/locales/pt-BR/views/profiles.yml, config/routes.rb, test/controllers/profiles/goals_controller_test.rb, test/policies/profiles/goal_policy_test.rb
=> feat: Add goal show page

app/models/goal.rb, app/views/profiles/goals/show.html.erb, test/models/goal_test.rb
- Corrige o cálculo dos dias restantes da meta
- Corrige a página da meta para mostrar o avatar e handle do dono da meta
=> fix: Show user handle and avatar

app/policies/profiles/goal_policy.rb, app/views/profiles/goals/show.html.erb
Adiciona o método `allow!` no pre check de `Profiles::GoalPolicy`.
=> fix: Add allow! to goal policy

app/components/ui/counter/button_component.rb, app/components/ui/counter/component.html.erb, app/components/ui/counter/component.rb, app/components/ui/counter/decrement_button_component.html.erb, app/components/ui/counter/decrement_button_component.rb, app/components/ui/counter/increment_button_component.html.erb, app/components/ui/counter/increment_button_component.rb, app/components/ui/counter/input_component.rb, app/components/ui/counter/preview.rb, app/components/ui/counter/previews/playground.html.erb, app/javascript/controllers/railsui/counter_input_controller.js, test/components/ui/counter_component_test.rb
Adiciona o componente `Counter`.
=> feat: Add a counter component

app/models/entry.rb, app/models/mention.rb, db/migrate/20250327224528_create_mentions.rb, db/schema.rb, test/factories/mentions.rb, test/models/mention_test.rb
Adiciona o model `Mention` que serve para representar menções de usuários em modelos do tipo `Entry`.
=> feat: Add mention model

app/controllers/notifications_controller.rb, app/views/layouts/_header.html.erb, app/views/notifications/_empty_state.html.erb, app/views/notifications/_notification.html.erb, app/views/notifications/index.html.erb, config/locales/pt-BR/views/notifications.yml, config/routes.rb, test/controllers/notifications_controller_test.rb
=> feat: Add notifications list and delete actions

app/components/features/mentions/mention/component.rb, app/components/features/mentions/mention/preview.rb, app/models/comment.rb, app/models/entry.rb, app/models/entry/content_parser.rb, app/models/entry/fragment.rb, app/models/entry/renderer.rb, app/models/mention.rb, app/models/post.rb, app/views/entries/entryables/_comment.html.erb, app/views/entries/entryables/_post.html.erb, test/components/features/mentions/mention_test.rb, test/models/entry/content_parser_test.rb, test/models/entry/fragment_test.rb, test/models/entry/renderer_test.rb, test/models/entry_test.rb, test/models/mention_test.rb
Renderiza as mentions de uma entry:
=> feat: Render mentions

app/components/ui/typography/component.rb, app/components/ui/typography/preview.rb, test/components/ui/typography_component_test.rb
Implementa um componente de tipografia:
=> feat: Add a typography component

app/views/layouts/_header.html.erb
- Limita o número de notificações mostradas no componente de lista para 5
- Ordena as notificações pela ordem de criação decrescente
=> feat: Limit the number of notifications shown

app/components/features/notifications/item_component.rb, app/components/features/notifications/list_component.html.erb, app/components/features/notifications/types/notification_comment_component.html.erb, app/components/features/notifications/types/notification_comment_component.rb, app/models/comment.rb, app/models/entry.rb, config/initializers/event_subscriber.rb, config/locales/pt-BR/features.yml, test/components/features/notifications/types/notification_comment_component_test.rb, test/models/comment_test.rb
=> feat: Send push notification when a comment is created

Gemfile.lock, Procfile.dev, app/components/features/notifications/item_component.html.erb, app/components/features/notifications/toggle_component.rb, app/controllers/notifications_controller.rb, app/controllers/read_all_notifications_controller.rb, app/models/goal/progress_change.rb, app/models/user.rb, app/models/user_notification.rb, app/models/user_notification_scopes.rb, app/views/goals/index.html.erb, app/views/layouts/_header.html.erb, test/components/features/notifications/list_component_test.rb, test/controllers/read_all_notifications_controller_test.rb, test/models/user_notification_test.rb
- Remove queries n + 1 da central de notificações
- Adiciona cache na central de notificações
- Adiciona cache na listagem de metas
**Antes:**
**Depois:**
=> refactor: Add performance improvements

app/assets/stylesheets/application.tailwind.css, config/deploy.yml
Muda a cor da barra de progresso do turbo:
=> feat: Change turbo's progress bar color

app/components/features/chats/inbox_panel/chat_item_component.html.erb, app/components/features/chats/inbox_panel/chat_item_component.rb, app/components/features/chats/inbox_panel/chat_list_component.html.erb, app/components/features/chats/inbox_panel/chat_list_component.rb, app/components/features/chats/inbox_panel/component.html.erb, app/components/features/chats/inbox_panel/component.rb, app/components/features/chats/inbox_panel/preview.rb, app/components/features/chats/inbox_panel/search_section_component.html.erb, app/components/features/chats/inbox_panel/search_section_component.rb, test/components/features/chats/inbox_panel_component_test.rb
Adiciona um componente chamado `Chats::InboxPanel::Component`:
=> feat: Add an inbox panel component

app/components/features/notifications/item_component.rb, app/components/features/notifications/types/notification_follow_component.html.erb, app/components/features/notifications/types/notification_follow_component.rb, app/controllers/follows_controller.rb, app/models/follow.rb, app/models/notification_factory.rb, app/models/notification_notifier.rb, config/initializers/event_subscriber.rb, config/locales/pt-BR/features.yml, test/components/features/notifications/types/notification_follow_component_test.rb, test/models/notification_factory_test.rb, test/models/notification_notifier_test.rb
=> feat: Add notification follow event

app/components/ui/timeline/badge_component.html.erb, app/components/ui/timeline/badge_component.rb, app/components/ui/timeline/body_component.html.erb, app/components/ui/timeline/body_component.rb, app/components/ui/timeline/component.html.erb, app/components/ui/timeline/component.rb, app/components/ui/timeline/item_component.html.erb, app/components/ui/timeline/item_component.rb, app/components/ui/timeline/preview.rb, test/components/ui/timeline_component_test.rb
Adiciona um componente de timeline:
=> Add a timeline component
